{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ezzenix",
    "module": "emlib",
    "version": "1.0.2+26.1-neoforge-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "emlib-1.0.2+26.1-neoforge-SNAPSHOT.jar",
          "url": "emlib-1.0.2+26.1-neoforge-SNAPSHOT.jar",
          "size": 696414,
          "sha512": "e91a52df4b0b92709b7928c7dfc9ac4f491579b5dc72b0c5985c640099e7d2b8b8ca2c7ee55382cc43755813c6dde7ff84cd0d1eaee2a62b54a59474c57b6fdd",
          "sha256": "643bd0fc1ba3acbc69a201b28b81d4aa41579cd68a96b536cc4465b8cf1c1a7e",
          "sha1": "1b6e491e6d67cb09f91dfb5173108db5f43813da",
          "md5": "be12b3ec27f1443c51a28c547be83060"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "emlib-1.0.2+26.1-neoforge-SNAPSHOT.jar",
          "url": "emlib-1.0.2+26.1-neoforge-SNAPSHOT.jar",
          "size": 696414,
          "sha512": "e91a52df4b0b92709b7928c7dfc9ac4f491579b5dc72b0c5985c640099e7d2b8b8ca2c7ee55382cc43755813c6dde7ff84cd0d1eaee2a62b54a59474c57b6fdd",
          "sha256": "643bd0fc1ba3acbc69a201b28b81d4aa41579cd68a96b536cc4465b8cf1c1a7e",
          "sha1": "1b6e491e6d67cb09f91dfb5173108db5f43813da",
          "md5": "be12b3ec27f1443c51a28c547be83060"
        }
      ]
    }
  ]
}
