{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ezzenix",
    "module": "emlib",
    "version": "1.0.1+26.2-neoforge-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "emlib-1.0.1+26.2-neoforge-SNAPSHOT.jar",
          "url": "emlib-1.0.1+26.2-neoforge-SNAPSHOT.jar",
          "size": 696364,
          "sha512": "919fc41f6bf4f08f57d6c8e387372fc15ba6026d4db4d78cf6af61f0e81b3c2429b2acda103f89fc1156ceeed247663739f01dc26fac236128665f599eb0237e",
          "sha256": "45fac754d51191e6b1a720fc701d230fa6433130932db410517e7a18ba3cd827",
          "sha1": "1530ad9f043da9d89e8eca2b439de511809aac6d",
          "md5": "e2e6a68feffc54fe6cab7a91886bfa13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "emlib-1.0.1+26.2-neoforge-SNAPSHOT.jar",
          "url": "emlib-1.0.1+26.2-neoforge-SNAPSHOT.jar",
          "size": 696364,
          "sha512": "919fc41f6bf4f08f57d6c8e387372fc15ba6026d4db4d78cf6af61f0e81b3c2429b2acda103f89fc1156ceeed247663739f01dc26fac236128665f599eb0237e",
          "sha256": "45fac754d51191e6b1a720fc701d230fa6433130932db410517e7a18ba3cd827",
          "sha1": "1530ad9f043da9d89e8eca2b439de511809aac6d",
          "md5": "e2e6a68feffc54fe6cab7a91886bfa13"
        }
      ]
    }
  ]
}
