{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ezzenix",
    "module": "emlib",
    "version": "1.0.0+26.1-neoforge-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "emlib-1.0.0+26.1-neoforge-SNAPSHOT.jar",
          "url": "emlib-1.0.0+26.1-neoforge-SNAPSHOT.jar",
          "size": 691781,
          "sha512": "65280f407a055941ad9585a681972a4ced33cedde39feecc790430a90c9773570844354c718e9b346a7a1517981f5af11d8164a997a20755b6419184a6395001",
          "sha256": "364758f7b566110f0ca384529c6a596ef1175369eea472640ee615597dc0fa8c",
          "sha1": "c59db75f55a22239bf51b7901de02638b60057b4",
          "md5": "ea5f78ac908f48b2711ce67381d8588e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "emlib-1.0.0+26.1-neoforge-SNAPSHOT.jar",
          "url": "emlib-1.0.0+26.1-neoforge-SNAPSHOT.jar",
          "size": 691781,
          "sha512": "65280f407a055941ad9585a681972a4ced33cedde39feecc790430a90c9773570844354c718e9b346a7a1517981f5af11d8164a997a20755b6419184a6395001",
          "sha256": "364758f7b566110f0ca384529c6a596ef1175369eea472640ee615597dc0fa8c",
          "sha1": "c59db75f55a22239bf51b7901de02638b60057b4",
          "md5": "ea5f78ac908f48b2711ce67381d8588e"
        }
      ]
    }
  ]
}
