{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ezzenix",
    "module": "emlib",
    "version": "1.0.0+26.1-neoforge-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "emlib-1.0.0+26.1-neoforge-SNAPSHOT.jar",
          "url": "emlib-1.0.0+26.1-neoforge-SNAPSHOT.jar",
          "size": 691781,
          "sha512": "1fc054ec98271e549bcfd26490db352de9ef8256a84c115f026354f9b9b48b7e5da739aefefa539989d24e9a27e8ce1fbcc3acf2fe86b52e3342d31f81b89b0c",
          "sha256": "fb6381771bbcbdab76403fad70dabf96be7036734052eef0e52cfdc88e007cb1",
          "sha1": "9ce3e7323df1e1ac65616403fa572c4f4ce5a23b",
          "md5": "344caac30d32313eaeacfd98b136c322"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "emlib-1.0.0+26.1-neoforge-SNAPSHOT.jar",
          "url": "emlib-1.0.0+26.1-neoforge-SNAPSHOT.jar",
          "size": 691781,
          "sha512": "1fc054ec98271e549bcfd26490db352de9ef8256a84c115f026354f9b9b48b7e5da739aefefa539989d24e9a27e8ce1fbcc3acf2fe86b52e3342d31f81b89b0c",
          "sha256": "fb6381771bbcbdab76403fad70dabf96be7036734052eef0e52cfdc88e007cb1",
          "sha1": "9ce3e7323df1e1ac65616403fa572c4f4ce5a23b",
          "md5": "344caac30d32313eaeacfd98b136c322"
        }
      ]
    }
  ]
}
