{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ezzenix",
    "module": "emlib",
    "version": "1.0.4+26.3-neoforge-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "emlib-1.0.4+26.3-neoforge-SNAPSHOT.jar",
          "url": "emlib-1.0.4+26.3-neoforge-SNAPSHOT.jar",
          "size": 696350,
          "sha512": "3d39cec96f2bb7343c0a385e01e114854d96d97417e7d4942be293f756d514580f28b1d88b6b88f272b8c141bddf8328841e0255621c85807d85b95febb460ed",
          "sha256": "14eb0987d82f1bd13bb51a3756588546a36e5fa7048eff4e3f256900137bc137",
          "sha1": "f6970aa9ae2d0126c77f3652cbd0d306b89d13d3",
          "md5": "1fe2427b771f3873d2ec1722883639a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "emlib-1.0.4+26.3-neoforge-SNAPSHOT.jar",
          "url": "emlib-1.0.4+26.3-neoforge-SNAPSHOT.jar",
          "size": 696350,
          "sha512": "3d39cec96f2bb7343c0a385e01e114854d96d97417e7d4942be293f756d514580f28b1d88b6b88f272b8c141bddf8328841e0255621c85807d85b95febb460ed",
          "sha256": "14eb0987d82f1bd13bb51a3756588546a36e5fa7048eff4e3f256900137bc137",
          "sha1": "f6970aa9ae2d0126c77f3652cbd0d306b89d13d3",
          "md5": "1fe2427b771f3873d2ec1722883639a4"
        }
      ]
    }
  ]
}
