{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ezzenix",
    "module": "emlib",
    "version": "1.0.2+26.3-neoforge-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "emlib-1.0.2+26.3-neoforge-SNAPSHOT.jar",
          "url": "emlib-1.0.2+26.3-neoforge-SNAPSHOT.jar",
          "size": 696401,
          "sha512": "e1c6edb61594633fffc015bae628350d0e8cb0bad7c2d9028188a434035607ac1a177c31fa5e2a0eeab57f2fabdea240329b87782509f0dfca4c03f731f83160",
          "sha256": "b55bce63c36053f34e0e98fcd885c1df6b07d591bba7f67d001071e0be37c183",
          "sha1": "7390d03d98d1455420237f0e957456f1b2036959",
          "md5": "97395888c4817df6c6022423b9ed5dde"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "emlib-1.0.2+26.3-neoforge-SNAPSHOT.jar",
          "url": "emlib-1.0.2+26.3-neoforge-SNAPSHOT.jar",
          "size": 696401,
          "sha512": "e1c6edb61594633fffc015bae628350d0e8cb0bad7c2d9028188a434035607ac1a177c31fa5e2a0eeab57f2fabdea240329b87782509f0dfca4c03f731f83160",
          "sha256": "b55bce63c36053f34e0e98fcd885c1df6b07d591bba7f67d001071e0be37c183",
          "sha1": "7390d03d98d1455420237f0e957456f1b2036959",
          "md5": "97395888c4817df6c6022423b9ed5dde"
        }
      ]
    }
  ]
}
