{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ezzenix",
    "module": "emlib",
    "version": "1.0.0+26.2-neoforge-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "emlib-1.0.0+26.2-neoforge-SNAPSHOT.jar",
          "url": "emlib-1.0.0+26.2-neoforge-SNAPSHOT.jar",
          "size": 691751,
          "sha512": "b1e36469f98201892f0f57e9f15000611f6b3d4413972e5a7433ed36deb77ab84c986d674bcae555a8e1621a7ca3f831527ecb91e9283eb746a3dd1a931466eb",
          "sha256": "61e6be41fa0b7b4cb0562023817c4856e6505378113275469255ecb56628167d",
          "sha1": "e7f0f9fcbcd9a55ab37d3fb1183e13ea3aa2604d",
          "md5": "142db0a44a4dc2a6d0cb38ff83f328ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "emlib-1.0.0+26.2-neoforge-SNAPSHOT.jar",
          "url": "emlib-1.0.0+26.2-neoforge-SNAPSHOT.jar",
          "size": 691751,
          "sha512": "b1e36469f98201892f0f57e9f15000611f6b3d4413972e5a7433ed36deb77ab84c986d674bcae555a8e1621a7ca3f831527ecb91e9283eb746a3dd1a931466eb",
          "sha256": "61e6be41fa0b7b4cb0562023817c4856e6505378113275469255ecb56628167d",
          "sha1": "e7f0f9fcbcd9a55ab37d3fb1183e13ea3aa2604d",
          "md5": "142db0a44a4dc2a6d0cb38ff83f328ac"
        }
      ]
    }
  ]
}
