{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ezzenix",
    "module": "emlib",
    "version": "1.0.0+26.2-neoforge-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "emlib-1.0.0+26.2-neoforge-SNAPSHOT.jar",
          "url": "emlib-1.0.0+26.2-neoforge-SNAPSHOT.jar",
          "size": 691751,
          "sha512": "61a69da14a976f903da5875185383e7781472fcdd33f71176da2004c5c076478b1efb492ce4fd6e0055cfb450d1fde683ff873947bec087b3ea36341166ca017",
          "sha256": "274213dce8411c287c068b05c52628725e7e7129f7a93f6e0998e43a091c000e",
          "sha1": "ecd5e476f2aea49568c0110335dcdb96cd3cec4a",
          "md5": "54e36d4824911d627348fe9e9c9b7939"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "emlib-1.0.0+26.2-neoforge-SNAPSHOT.jar",
          "url": "emlib-1.0.0+26.2-neoforge-SNAPSHOT.jar",
          "size": 691751,
          "sha512": "61a69da14a976f903da5875185383e7781472fcdd33f71176da2004c5c076478b1efb492ce4fd6e0055cfb450d1fde683ff873947bec087b3ea36341166ca017",
          "sha256": "274213dce8411c287c068b05c52628725e7e7129f7a93f6e0998e43a091c000e",
          "sha1": "ecd5e476f2aea49568c0110335dcdb96cd3cec4a",
          "md5": "54e36d4824911d627348fe9e9c9b7939"
        }
      ]
    }
  ]
}
